"""baseline full schema

Revision ID: 204fe0cd3e88
Revises: 
Create Date: 2026-06-26 11:12:47.485120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '204fe0cd3e88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_table('contacts_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_type', sa.Enum('customer', 'supplier', 'employee', 'other', name='enum_contacts_contact_contact_type'), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts_contact'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crew_member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_crew_member_id'), 'conversations', ['crew_member_id'], unique=False)
    op.create_table('crew_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plank_scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_members')),
    sa.UniqueConstraint('username', name=op.f('uq_crew_members_username'))
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index('ix_events_entity_lookup', 'events', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_entity_type'), 'events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plank', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=201), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('full_name', name=op.f('uq_graph_nodes_full_name')),
    sa.UniqueConstraint('plank', 'entity', name='uq_graph_nodes_plank_entity')
    )
    op.create_index(op.f('ix_graph_nodes_plank'), 'graph_nodes', ['plank'], unique=False)
    op.create_table('inventory_stock_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('raw_material', 'component', 'finished_good', 'consumable', name='enum_inventory_stock_item_category'), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=255), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_stock_item')),
    sa.UniqueConstraint('sku', name=op.f('uq_inventory_stock_item_sku'))
    )
    op.create_table('inventory_warehouse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_warehouse')),
    sa.UniqueConstraint('code', name=op.f('uq_inventory_warehouse_code')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_warehouse_name'))
    )
    op.create_table('maker_channel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fee_percent', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('fee_fixed', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_channel')),
    sa.UniqueConstraint('name', name=op.f('uq_maker_channel_name'))
    )
    op.create_table('maker_design',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('idea', 'in_progress', 'released', 'retired', name='enum_maker_design_status'), nullable=True),
    sa.Column('themes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_design')),
    sa.UniqueConstraint('slug', name=op.f('uq_maker_design_slug'))
    )
    op.create_table('maker_format',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_unit', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_format')),
    sa.UniqueConstraint('name', name=op.f('uq_maker_format_name'))
    )
    op.create_table('maker_market_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('booth_fee', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_market_event'))
    )
    op.create_table('maker_recipe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('labor_minutes', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('labor_rate_per_hour', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_recipe'))
    )
    op.create_table('asset_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_versions_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_versions'))
    )
    op.create_index(op.f('ix_asset_versions_asset_id'), 'asset_versions', ['asset_id'], unique=False)
    op.create_table('contacts_address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts_contact.id'], name=op.f('fk_contacts_address_contact_id_contacts_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts_address'))
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('source_full_name', sa.String(length=201), nullable=False),
    sa.Column('target_full_name', sa.String(length=201), nullable=False),
    sa.Column('relation_name', sa.String(length=100), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_source_id_graph_nodes')),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_target_id_graph_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index(op.f('ix_graph_edges_source_full_name'), 'graph_edges', ['source_full_name'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_full_name'), 'graph_edges', ['target_full_name'], unique=False)
    op.create_table('inventory_stock_movement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('movement_type', sa.Enum('received', 'shipped', 'adjusted', 'transferred', name='enum_inventory_stock_movement_movement_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['stock_item_id'], ['inventory_stock_item.id'], name=op.f('fk_inventory_stock_movement_stock_item_id_inventory_stock_item')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouse.id'], name=op.f('fk_inventory_stock_movement_warehouse_id_inventory_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_stock_movement'))
    )
    op.create_table('invoicing_invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'cancelled', name='enum_invoicing_invoice_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts_contact.id'], name=op.f('fk_invoicing_invoice_customer_id_contacts_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoicing_invoice')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoicing_invoice_invoice_number'))
    )
    op.create_table('maker_design_source_art',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maker_design_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maker_design_source_art_asset_id_assets')),
    sa.ForeignKeyConstraint(['maker_design_id'], ['maker_design.id'], name=op.f('fk_maker_design_source_art_maker_design_id_maker_design')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_design_source_art'))
    )
    op.create_table('maker_design_writing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maker_design_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maker_design_writing_asset_id_assets')),
    sa.ForeignKeyConstraint(['maker_design_id'], ['maker_design.id'], name=op.f('fk_maker_design_writing_maker_design_id_maker_design')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_design_writing'))
    )
    op.create_table('maker_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('format_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['maker_design.id'], name=op.f('fk_maker_product_design_id_maker_design')),
    sa.ForeignKeyConstraint(['format_id'], ['maker_format.id'], name=op.f('fk_maker_product_format_id_maker_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_product'))
    )
    op.create_table('maker_recipe_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('qty_per_unit', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['inventory_stock_item.id'], name=op.f('fk_maker_recipe_line_material_id_inventory_stock_item')),
    sa.ForeignKeyConstraint(['recipe_id'], ['maker_recipe.id'], name=op.f('fk_maker_recipe_line_recipe_id_maker_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_recipe_line'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('invoicing_invoice_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoicing_invoice.id'], name=op.f('fk_invoicing_invoice_line_invoice_id_invoicing_invoice')),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_stock_item.id'], name=op.f('fk_invoicing_invoice_line_product_id_inventory_stock_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoicing_invoice_line'))
    )
    op.create_table('invoicing_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'check', 'bank_transfer', 'credit_card', 'other', name='enum_invoicing_payment_payment_method'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoicing_invoice.id'], name=op.f('fk_invoicing_payment_invoice_id_invoicing_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoicing_payment'))
    )
    op.create_table('maker_product_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'current', 'retired', name='enum_maker_product_version_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['maker_product.id'], name=op.f('fk_maker_product_version_product_id_maker_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_product_version'))
    )
    op.create_table('maker_product_version_mockups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maker_product_version_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maker_product_version_mockups_asset_id_assets')),
    sa.ForeignKeyConstraint(['maker_product_version_id'], ['maker_product_version.id'], name=op.f('fk_maker_product_version_mockups_maker_product_version_id_maker_product_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_product_version_mockups'))
    )
    op.create_table('maker_product_version_production_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maker_product_version_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_maker_product_version_production_files_asset_id_assets')),
    sa.ForeignKeyConstraint(['maker_product_version_id'], ['maker_product_version.id'], name=op.f('fk_maker_product_version_production_files_maker_product_version_id_maker_product_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_product_version_production_files'))
    )
    op.create_table('maker_variation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('product_version_id', sa.UUID(), nullable=True),
    sa.Column('finished_stock_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['finished_stock_id'], ['inventory_stock_item.id'], name=op.f('fk_maker_variation_finished_stock_id_inventory_stock_item')),
    sa.ForeignKeyConstraint(['product_version_id'], ['maker_product_version.id'], name=op.f('fk_maker_variation_product_version_id_maker_product_version')),
    sa.ForeignKeyConstraint(['recipe_id'], ['maker_recipe.id'], name=op.f('fk_maker_variation_recipe_id_maker_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_variation')),
    sa.UniqueConstraint('sku', name=op.f('uq_maker_variation_sku'))
    )
    op.create_table('maker_listing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'ended', name='enum_maker_listing_status'), nullable=True),
    sa.Column('pricing_tier', sa.Enum('retail', 'wholesale', name='enum_maker_listing_pricing_tier'), nullable=True),
    sa.Column('variation_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['maker_channel.id'], name=op.f('fk_maker_listing_channel_id_maker_channel')),
    sa.ForeignKeyConstraint(['variation_id'], ['maker_variation.id'], name=op.f('fk_maker_listing_variation_id_maker_variation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_listing'))
    )
    op.create_table('maker_production_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_cogs_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_cogs', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variation_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['maker_variation.id'], name=op.f('fk_maker_production_run_variation_id_maker_variation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_production_run'))
    )
    op.create_table('maker_sale',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('shipwright_nl', 'tally', 'manual', 'import', name='enum_maker_sale_source'), nullable=True),
    sa.Column('variation_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('market_event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['maker_channel.id'], name=op.f('fk_maker_sale_channel_id_maker_channel')),
    sa.ForeignKeyConstraint(['market_event_id'], ['maker_market_event.id'], name=op.f('fk_maker_sale_market_event_id_maker_market_event')),
    sa.ForeignKeyConstraint(['variation_id'], ['maker_variation.id'], name=op.f('fk_maker_sale_variation_id_maker_variation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maker_sale'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maker_sale')
    op.drop_table('maker_production_run')
    op.drop_table('maker_listing')
    op.drop_table('maker_variation')
    op.drop_table('maker_product_version_production_files')
    op.drop_table('maker_product_version_mockups')
    op.drop_table('maker_product_version')
    op.drop_table('invoicing_payment')
    op.drop_table('invoicing_invoice_line')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('maker_recipe_line')
    op.drop_table('maker_product')
    op.drop_table('maker_design_writing')
    op.drop_table('maker_design_source_art')
    op.drop_table('invoicing_invoice')
    op.drop_table('inventory_stock_movement')
    op.drop_index(op.f('ix_graph_edges_target_full_name'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_full_name'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('contacts_address')
    op.drop_index(op.f('ix_asset_versions_asset_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_table('maker_recipe')
    op.drop_table('maker_market_event')
    op.drop_table('maker_format')
    op.drop_table('maker_design')
    op.drop_table('maker_channel')
    op.drop_table('inventory_warehouse')
    op.drop_table('inventory_stock_item')
    op.drop_index(op.f('ix_graph_nodes_plank'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_type'), table_name='events')
    op.drop_index('ix_events_entity_lookup', table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('crew_members')
    op.drop_index(op.f('ix_conversations_crew_member_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('contacts_contact')
    op.drop_table('assets')
    # ### end Alembic commands ###
