"""initial keel tables

Revision ID: 72f9ef53dd03
Revises: 
Create Date: 2026-04-15 17:07:47.292980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72f9ef53dd03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plank_scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_members')),
    sa.UniqueConstraint('username', name=op.f('uq_crew_members_username'))
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index('ix_events_entity_lookup', 'events', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_entity_type'), 'events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plank', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=201), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('full_name', name=op.f('uq_graph_nodes_full_name')),
    sa.UniqueConstraint('plank', 'entity', name='uq_graph_nodes_plank_entity')
    )
    op.create_index(op.f('ix_graph_nodes_plank'), 'graph_nodes', ['plank'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('source_full_name', sa.String(length=201), nullable=False),
    sa.Column('target_full_name', sa.String(length=201), nullable=False),
    sa.Column('relation_name', sa.String(length=100), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_source_id_graph_nodes')),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_target_id_graph_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index(op.f('ix_graph_edges_source_full_name'), 'graph_edges', ['source_full_name'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_full_name'), 'graph_edges', ['target_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_target_full_name'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_full_name'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_nodes_plank'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_type'), table_name='events')
    op.drop_index('ix_events_entity_lookup', table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('crew_members')
    # ### end Alembic commands ###
