from __future__ import annotations

import argparse
import asyncio
import sys

from theseus.bootstrap import build_registry
from theseus.database import async_session_factory
from theseus.keel.export.exporter import export_all
from theseus.keel.seed.loader import seed_pack


async def run_seed(packs: str) -> dict:
    """Seed each comma-separated pack. Assumes the schema is already migrated —
    run `theseus migrate` first (the Docker entrypoint does). Commits once."""
    registry = build_registry()
    merged: dict = {}
    async with async_session_factory() as session:
        for pack in [p.strip() for p in packs.split(",") if p.strip()]:
            merged.update(await seed_pack(session, registry, pack))
        await session.commit()
    for full_name, counts in merged.items():
        print(f"[seed] {full_name}: +{counts['created']} created, {counts['skipped']} skipped")
    return merged


async def run_export(out: str) -> str:
    registry = build_registry()
    async with async_session_factory() as session:
        await export_all(session, registry, out)
    print(f"[export] wrote {out}")
    return out


def run_migrate() -> None:
    """Apply Alembic migrations (upgrade to head) against settings.database_url_sync."""
    from alembic import command
    from alembic.config import Config

    command.upgrade(Config("alembic.ini"), "head")
    print("[migrate] database at head")


def run_check_migrations(url: str) -> int:
    """Drift gate: reset a DISPOSABLE db's public schema, upgrade to head, then
    `alembic check` — fails if the migrations don't match the declared metadata
    (e.g. a Blueprint was edited without generating a migration). DESTRUCTIVE to
    `url` — never point it at prod."""
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected
    from sqlalchemy import create_engine, text

    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))
    engine.dispose()

    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", url)
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        print(f"[check-migrations] DRIFT: {exc}")
        return 1
    print("[check-migrations] OK: migrations match the declared schema")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="theseus", description="Theseus ERP admin CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    seed_p = sub.add_parser("seed", help="Seed default lookups for one or more packs")
    seed_p.add_argument("--packs", required=True, help="comma-separated pack names, e.g. maker")

    export_p = sub.add_parser("export", help="Export all data to a zip (CSV + asset files)")
    export_p.add_argument("--out", required=True, help="output .zip path")

    sub.add_parser("migrate", help="Apply Alembic migrations (upgrade to head)")

    check_p = sub.add_parser(
        "check-migrations",
        help="DESTRUCTIVE drift gate: reset a disposable DB, upgrade, alembic check",
    )
    check_p.add_argument(
        "--url", required=True,
        help="SYNC url of a DISPOSABLE database (its public schema is reset)",
    )

    args = parser.parse_args(argv)
    try:
        if args.command == "seed":
            asyncio.run(run_seed(args.packs))
        elif args.command == "export":
            asyncio.run(run_export(args.out))
        elif args.command == "migrate":
            run_migrate()
        elif args.command == "check-migrations":
            return run_check_migrations(args.url)
    except Exception as exc:
        print(f"[theseus] {args.command} failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
