from __future__ import annotations
from typing import Protocol
from theseus.keel.knowledge_graph.models import GraphEdgeRecord, GraphNodeRecord


class KnowledgeGraphProtocol(Protocol):
    async def register_entity_type(self, plank: str, entity: str, description: str) -> GraphNodeRecord: ...
    async def register_relationship_type(self, source: str, target: str, relation_name: str, relation_type: str) -> GraphEdgeRecord: ...
    async def get_entity_type(self, full_name: str) -> GraphNodeRecord | None: ...
    async def get_related_types(self, full_name: str) -> list[GraphNodeRecord]: ...
    async def get_types_by_plank(self, plank: str) -> list[GraphNodeRecord]: ...
