from __future__ import annotations
from typing import Any, Protocol
from theseus.keel.auth.models import CrewMemberRecord, CrewRole


class AuthServiceProtocol(Protocol):
    async def create_crew_member(self, *, username: str, password: str, display_name: str, role: CrewRole, plank_scopes: list[str] | None = None) -> CrewMemberRecord: ...
    async def authenticate(self, username: str, password: str) -> CrewMemberRecord | None: ...
    def create_access_token(self, member: CrewMemberRecord) -> str: ...
    def verify_access_token(self, token: str) -> dict[str, Any] | None: ...
